development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: dynamic-authorisation-app_development
  user: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: dynamic-authorisation-app_test
  user: postgres
  password: postgres
  host: localhost
  port: 5432
